name: 🐛 Bug Report
description: File a bug/issue report to help us improve
title: "[BUG] <title>"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expect to happen?
      placeholder: How this thing needs to work!

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Steps to reproduce bug
      description: Describe how you reach to bug & steps to regenerate that bug?
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

  - type: textarea
    attributes:
      label: Environment
      placeholder: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
        - OS:
        - Node:
        - npm:

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]([TODO:\ update url])
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: |
        > Thanks for taking the time to fill out this bug report!
