name: 🏗️ Feature request
description: Suggest an idea for this project
title: <title>
labels: [enhancement, feature request]
body:
  - type: textarea
    id: define-problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: define-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I want that div should be in center

  - type: textarea
    id: define-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: checkboxes
    id: handle-myself
    attributes:
      label: You want to work on that issue
      options:
        - label: I want to work on that feature request

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]([TODO:/ update url])
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: |
        > Thanks for submit this feature request!
